IF (LIBYAML_INCLUDE_DIR)
  # Already in cache, be silent
  SET(LIBYAML_FIND_QUIETLY TRUE)
ENDIF (LIBYAML_INCLUDE_DIR)

FIND_PATH(LIBYAML_INCLUDE_DIR yaml.h)
 
IF(LIBYAML_INCLUDE_DIR) 
   SET(LIBYAML_FOUND TRUE) 
ENDIF(LIBYAML_INCLUDE_DIR) 

IF(LIBYAML_FOUND) 
  set(CMAKE_REQUIRED_INCLUDES ${LIBYAML_INCLUDE_DIR})
  set(CMAKE_REQUIRED_INCLUDES)
  IF(NOT LIBYAML_FIND_QUIETLY) 
    MESSAGE(STATUS "Found LIBYAML headers: ${LIBYAML_INCLUDE_DIR}/yaml.h") 
  ENDIF(NOT LIBYAML_FIND_QUIETLY) 
ELSE(LIBYAML_FOUND) 
  IF(LibYAML_FIND_REQUIRED) 
    MESSAGE(FATAL_ERROR "Could not find LIBYAML") 
  ENDIF(LibYAML_FIND_REQUIRED) 
ENDIF(LIBYAML_FOUND) 

MARK_AS_ADVANCED(
  LIBYAML_INCLUDE_DIR
  LIBYAML_LIBRARIES
)
